### ISSUE TITLE
Is there any more  detailed Useage?

### ISSUE THREAD

**Issue by miss85246** [hlf20010508/minio-async#1]
It's looks very cool, but is there any more  detailed Useage?

**Comment by hlf20010508** [comment]
> It's looks very cool, but is there any more detailed Useage?

Well you can refer to
- [https://github.com/hlf20010508/transfery/blob/master/run.py](https://github.com/hlf20010508/transfery/blob/master/run.py)
- [https://github.com/hlf20010508/transfery/blob/master/OSS_minio.py](https://github.com/hlf20010508/transfery/blob/master/OSS_minio.py)

The initualization is the same as original minio python API.
You need to use other modules which support async, or use `asyncio` to manually run it

Here is the simple example:
```Python
from minio_async import Minio
import asyncio

client = Minio(
    endpoint="Your host",
    access_key="Your username",
    secret_key="Your password",
    secure=False  # http for False, https for True
)

loop = asyncio.get_event_loop()
res = loop.run_until_complete(client.presigned_get_object("Your bucket name", "Your object name"))
print('Got presigned url:', res)
loop.close()
```

**Comment by hlf20010508** [comment]
I've added some examples [here](https://github.com/hlf20010508/minio-async/tree/master/example) and updated readme.
More examples will be added in the future is I have time.
